# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dd97b481e61d6a5fc5b1ac61f1ecc5afba15d3f7a731436665fe6e7b689f4e95656f31b646674c37cd73467870b670c0950898cecd1c281b999180e286fca1b

test:
  secret_key_base: 2300a52b7cd0133584ca2ec1afcc307374939b07fce8ddfe227bc782239417eb284c8eebab220215496d1801761744d94656c3dddf176ffd00caca9e54945a2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
